name: run-trivy
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  build:
    name: run trivy action
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Build an image from Dockerfile
        run: |
          docker build https://raw.githubusercontent.com/CatTheCatch/Terragoat/main/terraform/aws/resources/Dockerfile -t bartek/test-image:v1
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'bartek/test-image:v1'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
